version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # 持久化H2数据库文件（如果使用文件模式）
      - ./backend/data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JWT_SECRET=${JWT_SECRET:-travelplanner-secret-key-2024-very-secure-jwt-token-for-hs512-algorithm-must-be-at-least-512-bits-long}
      # AI服务配置 - 可以通过环境变量或.env文件设置
      - QWEN_API_KEY=${QWEN_API_KEY:-}
      - XUNFEI_APP_ID=${XUNFEI_APP_ID:-your_xunfei_app_id}
      - XUNFEI_API_KEY=${XUNFEI_API_KEY:-your_xunfei_api_key}
      - XUNFEI_API_SECRET=${XUNFEI_API_SECRET:-your_xunfei_api_secret}
    restart: unless-stopped
    # 添加网络配置以确保可以访问外部API
    network_mode: "bridge"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped