version: '3.8'

services:
  travel-planner:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # 持久化SQLite数据库文件
      - ./backend/data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JWT_SECRET=travelplanner-secret-key-2024
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s