server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: travel-planner
  
  # 数据库配置 - H2内存数据库（开发/默认）
  datasource:
    url: jdbc:h2:mem:travel_planner;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
    
  # SQL初始化配置
  sql:
    init:
      mode: always
      continue-on-error: false
        
  # Jackson配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

# 日志配置
logging:
  level:
    com.travelplanner: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 自定义配置
app:
  # JWT配置
  jwt:
    secret: ${JWT_SECRET:travelplanner-secret-key-2024-very-secure-jwt-token-for-hs512-algorithm-must-be-at-least-512-bits-long}
    expiration: 86400000 # 24小时
    
    
  # 科大讯飞API配置
  # 请访问 https://www.xfyun.cn/ 获取API密钥
  # 1. 注册/登录科大讯飞开放平台
  # 2. 创建应用，选择"语音听写"服务
  # 3. 获取APPID、API Key、API Secret
  # 4. 替换下面的配置值或设置环境变量
  xunfei:
    app-id: ${XUNFEI_APP_ID:your_xunfei_app_id}  # 您的APPID
    api-key: ${XUNFEI_API_KEY:your_xunfei_api_key}  # 您的API Key
    api-secret: ${XUNFEI_API_SECRET:your_xunfei_api_secret}  # 您的API Secret
    base-url: https://api.xf-yun.com/v1/private
    
  # 阿里通义千问API配置
  qwen:
    api-key: ${QWEN_API_KEY:}  # 从环境变量或用户数据库获取
    base-url: https://dashscope.aliyuncs.com/api/v1
    model: qwen-turbo
    
  # AI服务配置
  ai:
    mock-mode: false  # 禁用桩程序模式，启用真正的通义千问API调用
